<?php

namespace api\modules\v1\User\models;

use Yii;
use yii\base\Exception;

class User extends \common\models\User
{
    /**
     * {@inheritdoc}
     */
    public static function tableName(): string
    {
        return '{{%user}}';
    }

    /**
     * @throws Exception
     */
    public function beforeSave($insert): bool
    {
        if (parent::beforeSave($insert)) {
            $this->setPasswordHash($this->password);
            $this->generateAuthKey();
            $this->generateAccessToken();
            $this->setIsDeleted();
        } else if (Yii::$app->request->post('password')) {
            $this->setPasswordHash(Yii::$app->request->post('password'));
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public static function find(): \yii\db\ActiveQuery
    {
        return parent::find()->where(['isDeleted' => 0]);
    }
}
